# Generated by Django 4.0.3 on 2022-06-13 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_soup'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_drinks', models.CharField(max_length=50, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Напиток (комплексный обед)',
                'verbose_name_plural': 'Напитки (комплексный обед)',
            },
        ),
        migrations.CreateModel(
            name='Salad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_salad', models.CharField(max_length=50, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Салат (комплексный обед)',
                'verbose_name_plural': 'Салаты (комплексный обед)',
            },
        ),
        migrations.CreateModel(
            name='Second_dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_second_dish', models.CharField(max_length=50, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Вторые блюда (комплексный обед)',
                'verbose_name_plural': 'Вторые блюда (комплексный обед)',
            },
        ),
        migrations.AlterModelOptions(
            name='number',
            options={'verbose_name': 'Основное меню', 'verbose_name_plural': 'Основное меню'},
        ),
        migrations.AlterModelOptions(
            name='soup',
            options={'verbose_name': 'Супы (комплексный обед)', 'verbose_name_plural': 'Супы (комплексный обед)'},
        ),
    ]
