# Generated by Django 4.0.3 on 2022-06-22 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_drinks_salad_second_dish_alter_number_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Number',
        ),
    ]
