# Generated by Django 4.0.3 on 2022-06-13 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('count', models.IntegerField(verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Авторские напитки',
                'verbose_name_plural': 'Авторские напитки',
            },
        ),
        migrations.CreateModel(
            name='Author_drinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('count', models.IntegerField(verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Напитки собственного производства',
                'verbose_name_plural': 'Напитки собственного производства',
            },
        ),
        migrations.CreateModel(
            name='Coctails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('count', models.IntegerField(verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Коктейли безалкогольные',
                'verbose_name_plural': 'Коктейли безалкогольные',
            },
        ),
        migrations.CreateModel(
            name='Coffee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('count', models.IntegerField(verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Кофе',
                'verbose_name_plural': 'Чай',
            },
        ),
        migrations.CreateModel(
            name='Dessert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('count', models.IntegerField(verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Десерт',
                'verbose_name_plural': 'Десерт',
            },
        ),
        migrations.CreateModel(
            name='Juice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('count', models.IntegerField(verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Соки',
                'verbose_name_plural': 'Соки',
            },
        ),
        migrations.CreateModel(
            name='Main',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('count', models.IntegerField(verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Основное',
                'verbose_name_plural': 'Основное',
            },
        ),
        migrations.CreateModel(
            name='Rus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('count', models.IntegerField(verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'А-ля русс',
                'verbose_name_plural': 'А-ля русс',
            },
        ),
        migrations.CreateModel(
            name='Salad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('count', models.IntegerField(verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Салаты',
                'verbose_name_plural': 'Салаты',
            },
        ),
        migrations.CreateModel(
            name='Tea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('count', models.IntegerField(verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Чай',
                'verbose_name_plural': 'Чай',
            },
        ),
        migrations.CreateModel(
            name='Water',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('count', models.IntegerField(verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Вода',
                'verbose_name_plural': 'Вода',
            },
        ),
        migrations.CreateModel(
            name='Сarbonated',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('count', models.IntegerField(verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Газированные напитки',
                'verbose_name_plural': 'Газированные напитки',
            },
        ),
        migrations.AlterModelOptions(
            name='main_menu',
            options={'verbose_name': 'Закуски', 'verbose_name_plural': 'Закуски'},
        ),
    ]
