# Generated by Django 4.0.3 on 2022-06-13 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_author_author_drinks_coctails_coffee_dessert_juice_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Сarbonated',
            new_name='Carbon',
        ),
        migrations.AlterModelOptions(
            name='coffee',
            options={'verbose_name': 'Кофе', 'verbose_name_plural': 'Кофе'},
        ),
        migrations.AddField(
            model_name='salad',
            name='description',
            field=models.TextField(default=1, verbose_name='Описание'),
            preserve_default=False,
        ),
    ]
