# Generated by Django 4.0.3 on 2022-06-13 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_main_menu_description_alter_salad_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Soup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('count', models.IntegerField(verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Супы',
                'verbose_name_plural': 'Супы',
            },
        ),
    ]
